# Generated by Django 5.2.6 on 2025-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0013_rename__admin_roles_ancillary_admin_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='energy_per_pulse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Energy per pulse'),
        ),
        migrations.AddField(
            model_name='facility',
            name='pulse_duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pulse Duration'),
        ),
        migrations.AddField(
            model_name='facility',
            name='repetition_rate',
            field=models.CharField(max_length=255, null=True, verbose_name='Repetition Rate'),
        ),
    ]
